name: CI

on:
  push:
    branches:
      - develop
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: kikirartcollection/kikirartcollection.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: kikirartcollection
          user_email: kikirartcollection@gmail.com
          publish_branch: main
          #   cname: example.com